# Deployment do controle-temperatura
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-temperatura
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web-temperatura
  template:
    metadata:
      labels:
        app: web-temperatura
    spec:
      containers:
        - name: web-temperatura
          image: fabricioveronez/controle-temperatura:v1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: web-temperatura
spec:
  selector:
    app: web-temperatura
  ports:
    - port: 80
      targetPort: 8080
      NodePort: 30000
      protocol: TCP
  type: NodePort 